<table class="dataTable crop">
    <thead>
        <tr>
            <td>Crop Type</td>
            <td>Shelf Life</td>
            <td></td>
        </tr>
    </thead>
    <tbody>
        
                
<?php 

    if(is_array($this->crops))
    { 
        $data = $this->crops;
        
        foreach($data as $item)
        {  
?>        
            <tr>
                <td><?php echo $item['cropType']; ?></td>
                <td><?php echo $item['shelfLife']; ?></td>
                <td><a href="<?php echo $this->url(array('action' => 'view', 'controller' => 'crop', 'module' => 'app', 'cropId' => $item['cropId'])); ?>">View</a></td>
            </tr>
<?php
        }
    }
?>
    </tbody>
</table>


