<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="initial-scale=1.0">
  <title>AgroLogistics</title>
  <link href="<?php  echo Zend_controller_front::getInstance()->getBaseUrl(); ?>/css/bootstrap.min.css" rel="stylesheet" media="screen">
    
    <script src="<?php  echo Zend_controller_front::getInstance()->getBaseUrl(); ?>/js/jquery/jquery.min.js"></script>
    <script src="<?php  echo Zend_controller_front::getInstance()->getBaseUrl(); ?>/js/bootstrap.min.js"></script>
    
  <link rel="stylesheet" href="<?php  echo Zend_controller_front::getInstance()->getBaseUrl(); ?>/theme/css/standardize.css">
  <link rel="stylesheet" href="<?php  echo Zend_controller_front::getInstance()->getBaseUrl(); ?>/theme/css/index-grid.css">
  <link rel="stylesheet" href="<?php  echo Zend_controller_front::getInstance()->getBaseUrl(); ?>/theme/css/index.css">
  
  <link rel="stylesheet" href="<?php  echo Zend_controller_front::getInstance()->getBaseUrl(); ?>/css/main.css">
  
</head>
<body class="body index clearfix">
    <div class="title_block clearfix">
        <a class="home-logo" href="/AgroLogistics/public/test"></a>
        <h1 class="title">AGROLOGISTICS</h1>
        <div class="menu">
          <a class="menu ship"  href="/AgroLogistics/public/app/ship">Cargo Ships</a>
          <a class="menu crop"  href="/AgroLogistics/public/app/crop">Crops</a>
        </div>
    </div>
    <div class="content_container">
        <div class="container agroMainContent">
            <?php echo $this->layout()->content; ?>
        </div>
    </div>
    <div id="footer">
        <div class="container">
            <p class="muted credit">Copyright &copy;2014 AgroLogistics</p>
        </div>
    </div>
</body>
</html>