<!DOCTYPE html>
<html>
<head>
    <title>AgroLogistics</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link href="<?php  echo Zend_controller_front::getInstance()->getBaseUrl(); ?>/js/css/bootstrap.min.css" rel="stylesheet" media="screen">
    
    <script src="<?php  echo Zend_controller_front::getInstance()->getBaseUrl(); ?>/jquery/jquery.min.js"></script>
    <script src="<?php  echo Zend_controller_front::getInstance()->getBaseUrl(); ?>/js/bootstrap/bootstrap.min.js"></script>
</head>
<body>

    <div id="wrap">
        <div class="container wrap">
            <?php  echo $this->layout()->content; ?>
        </div>
    </div>
    <div id="footer">
        <div class="container">
            <p class="muted credit">Copyright &copy;2014 AgroLogistics</p>
        </div>
    </div>
</body>
</html

<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="initial-scale=1.0">
  <title>AgroLogistics</title>
  <link rel="stylesheet" href="css/standardize.css">
  <link rel="stylesheet" href="css/index-grid.css">
  <link rel="stylesheet" href="css/index.css">
</head>
<body class="body index clearfix">
  <div class="title_block clearfix">
    <button class="home-logo"></button>
    <h1 class="title">AGROLOGISTICS</h1>
  </div>
  <div class="content_container"></div>
</body>
</html>