<html>
    <head>
        <title>AgroLogistics Components Tests</title>
        <script src="jquery/jquery.min.js" type="text/javascript"></script>
    </head>
    
    <body>
        <div class="testing_api">
            <h1>AgroLogistics Components Tests</h1>
            
            <a href="<?php echo $this->test1; ?>"><h3>Reporting Component Test</h3></a>
            <a href="<?php echo $this->test2; ?>"><h3>Get Shipping Options to Destination Test</h3></a>
            <a href="<?php echo $this->test3; ?>"><h3>Get Products Available Test</h3></a>
        </div>
    </body>
</html>