
<form action="<?php echo $this->apiUrl; ?>" method="POST">
    <div class="testing_api">
        <h1>AgroLogistics ProductsAvailable Test</h1>

        <textarea id="requestData" name="requestData" rows="10" cols="280" style="width: 100%;">
        {
            "buyerLocation": "HAV",
            "cropType": "YAM"
        }
        </textarea>
        <input class="btn" type="submit" name="SUBMIT" value="Call Api" />
    </div>
</form>