<div>
    <form method="GET">
    <div class="order-select">
            <label>Location</label>
            <div class="value">
                <select name="buyerLocation" placeholder="Select a location">
        <?php
                    $this->locations = array('', 'HAV', 'MIA', 'GER', 'BEI', 'MAR', 'BAR', 'STL', 'CUR');
                    
                    foreach($this->locations as $location)
                    {
        ?>
                    <option value="<?php echo $location; ?>" <?php echo $selected = !empty($this->buyerLocation) && $this->buyerLocation == $location ? 'selected' : ''; ?>><?php echo $location; ?></option>
        <?php
                    }
        ?>
                </select>
            </div>
           
            <label>Crop Type</label>
            <div class="value">
                <select name="cropType" placeholder="Select a crop">
        <?php
                    $this->cropTypes = array('', 'Rice', 'Cattle', 'Pig', 'Soybeans', 'Tomatoes', 'SugarCane', 'Yam', 'Coconuts', 'Maize', 'Eggs', 'Potatoes');
                    
                    foreach($this->cropTypes as $cropType)
                    {
        ?>
                    <option value="<?php echo $cropType; ?>" <?php echo $selected = !empty($this->cropType) && $this->cropType == $cropType ? 'selected' : ''; ?>><?php echo $cropType; ?></option>
        <?php
                    }
        ?>
                </select>
            </div>   
        <button class="btn" type="submit">Go</button>
        </form>
    </div>
</div>

<?php
    if(!empty($this->buyerLocation))
    {
?>
<table class="dataTable crop">
    <thead>
        <tr>
            <td>Crop Type</td>
            <td>Quantity Available</td>
            <td>Delivery Date</td>
            <td></td>
        </tr>
    </thead>
    <tbody>
        
<?php 

    if(is_array($this->crops))
    { 
        $data = $this->crops;
        
        foreach($data as $item)
        {  
?>          
                <tr>
                    <td><?php echo $item['cropType']; ?></td>
                    <td><?php echo $item['maximumQuantity']; ?></td>
                    <td><?php echo $item['dateAvailable']; ?></td>
                    <td><a href="<?php echo $this->url(array('action' => 'confirm-order', 'controller' => 'order', 'module' => 'app', 'cropId' => $item['cropId'], 'maximumQuantity' => $item['maximumQuantity'])); ?>">Place Order</a></td>
                </tr>
<?php
        }
    }
?>


    </tbody>
</table>

<?php
    }
    else
    {
?>
        <div class="alert alert-info">
            <p class="error">Please choose your location from above to get started.</p>
        </div>
<?php
    }
?>
